version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
    restart: unless-stopped
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:5000
    restart: unless-stopped
